version: '2'

services:
    mysql:
        image: mysql
        restart: 'no'
        env_file:
           - variables.env
        # volumes:
        #     - ./data/mysql:/docker-entrypoint-initdb.d
    nginx:
        depends_on:
            - phpfpm
        image: nginx
        ports:
            - "80:80"
        restart: 'no'
        working_dir: /var/www
        volumes:
            - ../app:/var/www/
            - ./conf/nginx/drupal.conf:/etc/nginx/conf.d/default.conf
    phpfpm:
        image: phalconphp/php-apache:ubuntu-16.04
        restart: 'no'
        working_dir: /var/www
        ports:
            - "8080:80"
        volumes:
            - ../app:/var/www
        depends_on:
            - mysql
   
